### ISSUE TITLE
Contact Form UI 

### ISSUE THREAD

**Issue by tanishq-arya** [khannakshat7/Elektra#6]
It is good idea to have a contact form in the contact section. As a GSSOC participant I would like to work on the frontend part of the form. I have given a screen shot of idea I have in mind. I will match it with the design of the website. You can check out the SASS repository in my profile for the full page view. 
![Screenshot (938)](https://user-images.githubusercontent.com/77333275/110421079-c4e0a700-80c2-11eb-994a-69d062491108.png)
.

**Comment by khannakshat7** [comment]
Ok, @tanishq-arya You can make a contact form but you should match it with the theme of the project. I am assigning the issue. You can start contributing to it.

**Comment by tanishq-arya** [comment]
Thankyou for assigning me the issue. I'm having trouble viewing the website on my machine, can you help me with that. I can only see the static website. I have to run main.py right ? I installed django but I'm unable to install mysqlclient and main.py won't run without it.

**Comment by khannakshat7** [comment]
Just run the command `pip install mysqlclient`
Then run the manage.py file using command `python manage.py runserver`

No need to run main.py file

**Comment by tanishq-arya** [comment]
okay

**Comment by tanishq-arya** [comment]
Getting the following errors
PS D:\Elektra> python manage.py runserver 
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\Users\Tanishq\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\backends\base\base.py", line 219, in ensure_connection
    self.connect()
  File "C:\Users\Tanishq\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Users\Tanishq\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\backends\base\base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "C:\Users\Tanishq\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Users\Tanishq\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\backends\mysql\base.py", line 234, in get_new_connection
    return Database.connect(**conn_params)
  File "C:\Users\Tanishq\AppData\Local\Programs\Python\Python38-32\lib\site-packages\MySQLdb\__init__.py", line 84, in Connect
    return Connection(*args, **kwargs)
  File "C:\Users\Tanishq\AppData\Local\Programs\Python\Python38-32\lib\site-packages\MySQLdb\connections.py", line 179, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
MySQLdb._exceptions.OperationalError: (1045, "Access denied for user 'ODBC'@'localhost' (using password: NO)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Tanishq\AppData\Local\Programs\Python\Python38-32\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\Tanishq\AppData\Local\Programs\Python\Python38-32\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Tanishq\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\utils\autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\Tanishq\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\core\management\commands\runserver.py", line 121, in inner_run
    self.check_migrations()
  File "C:\Users\Tanishq\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\core\management\base.py", line 459, in check_migrations
    executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
  File "C:\Users\Tanishq\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\migrations\executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "C:\Users\Tanishq\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\migrations\loader.py", line 53, in __init__
    self.build_graph()
  File "C:\Users\Tanishq\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\migrations\loader.py", line 216, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "C:\Users\Tanishq\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\migrations\recorder.py", line 77, in applied_migrations
    if self.has_table():
  File "C:\Users\Tanishq\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\migrations\recorder.py", line 55, in has_table
    with self.connection.cursor() as cursor:
  File "C:\Users\Tanishq\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Users\Tanishq\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\backends\base\base.py", line 259, in cursor
    return self._cursor()
  File "C:\Users\Tanishq\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\backends\base\base.py", line 235, in _cursor
    self.ensure_connection()
  File "C:\Users\Tanishq\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Users\Tanishq\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\backends\base\base.py", line 219, in ensure_connection
    self.connect()
  File "C:\Users\Tanishq\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Tanishq\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\backends\base\base.py", line 219, in ensure_connection
    self.connect()
  File "C:\Users\Tanishq\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Users\Tanishq\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\backends\base\base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "C:\Users\Tanishq\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "C:\Users\Tanishq\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\db\backends\mysql\base.py", line 234, in get_new_connection
    return Database.connect(**conn_params)
  File "C:\Users\Tanishq\AppData\Local\Programs\Python\Python38-32\lib\site-packages\MySQLdb\__init__.py", line 84, in Connect
    return Connection(*args, **kwargs)
  File "C:\Users\Tanishq\AppData\Local\Programs\Python\Python38-32\lib\site-packages\MySQLdb\connections.py", line 179, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
django.db.utils.OperationalError: (1045, "Access denied for user 'ODBC'@'localhost' (using password: NO)")

**Comment by khannakshat7** [comment]
Check your MySQL database username and password in settings.py file

**Comment by tanishq-arya** [comment]
I have made some changes to the contact and footer. Now I'll be working on the responsiveness of the form. I am attaching an update screenshot.
![Screenshot (941)](https://user-images.githubusercontent.com/77333275/110438787-bef7bf80-80dc-11eb-81c0-55ce198e019a.png)

Below is an design idea I was thinking when we hover over the submit button.
![Screenshot (940)](https://user-images.githubusercontent.com/77333275/110438943-ddf65180-80dc-11eb-99a7-dd6e225dfda6.png)

**Comment by khannakshat7** [comment]
Great work @tanishq-arya!! Go ahead and work on responsive form

**Comment by tanishq-arya** [comment]
I need a clarification. I have to stage commits only to the style.css and html.css right ? The changes to settings.py were to my machine only.

**Comment by khannakshat7** [comment]
yes don't commit settings.py file

**Comment by khannakshat7** [comment]
just fork the project, commit the files u have changed and push it to your
FORK REPO. Then just make a pull request to this repo

**Comment by tanishq-arya** [comment]
Okay got it.

**Comment by tanishq-arya** [comment]
Also could you please add the label GSSOC'21 to the issue.

**Comment by tanishq-arya** [comment]
#17 I have solved this issue
